
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("bbe41fd1-6c36-4eaf-bcee-742ba32e6546")>
Namespace SharePointDataSource.Implementation

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class SharePointDataSourceObjectContext
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new SharePointDataSourceObjectContext object using the connection string found in the 'SharePointDataSourceObjectContext' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=SharePointDataSourceObjectContext", "SharePointDataSourceObjectContext")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new SharePointDataSourceObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "SharePointDataSourceObjectContext")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new SharePointDataSourceObjectContext object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "SharePointDataSourceObjectContext")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property Timesheets() As ObjectSet(Of Timesheet)
            Get
                If (_Timesheets Is Nothing) Then
                    _Timesheets = MyBase.CreateObjectSet(Of Timesheet)("Timesheets")
                End If
                Return _Timesheets
            End Get
        End Property
    
        Private _Timesheets As ObjectSet(Of Timesheet)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the Timesheets EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToTimesheets(ByVal timesheet As Timesheet)
            MyBase.AddObject("Timesheets", timesheet)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="LightSwitchApplication", Name:="Timesheet")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class Timesheet
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new Timesheet object.
        ''' </summary>
        ''' <param name="timesheetId">Initial value of the TimesheetId property.</param>
        Public Shared Function CreateTimesheet(timesheetId As Global.System.Int32) As Timesheet
            Dim timesheet as Timesheet = New Timesheet
            timesheet.TimesheetId = timesheetId
            Return timesheet
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property TimesheetId() As Global.System.Int32
            Get
                Return _TimesheetId
            End Get
            Set
                If (_TimesheetId <> Value) Then
                    OnTimesheetIdChanging(value)
                    ReportPropertyChanging("TimesheetId")
                    _TimesheetId = value
                    ReportPropertyChanged("TimesheetId")
                    OnTimesheetIdChanged()
                End If
            End Set
        End Property
    
        Private _TimesheetId As Global.System.Int32
        Private Partial Sub OnTimesheetIdChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnTimesheetIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Project() As Global.System.String
            Get
                Return _Project
            End Get
            Set
                OnProjectChanging(value)
                ReportPropertyChanging("Project")
                _Project = value
                ReportPropertyChanged("Project")
                OnProjectChanged()
            End Set
        End Property
    
        Private _Project As Global.System.String
        Private Partial Sub OnProjectChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnProjectChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Client() As Global.System.String
            Get
                Return _Client
            End Get
            Set
                OnClientChanging(value)
                ReportPropertyChanging("Client")
                _Client = value
                ReportPropertyChanged("Client")
                OnClientChanged()
            End Set
        End Property
    
        Private _Client As Global.System.String
        Private Partial Sub OnClientChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnClientChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property UserId() As Nullable(Of Global.System.Int32)
            Get
                Return _UserId
            End Get
            Set
                OnUserIdChanging(value)
                ReportPropertyChanging("UserId")
                _UserId = value
                ReportPropertyChanged("UserId")
                OnUserIdChanged()
            End Set
        End Property
    
        Private _UserId As Nullable(Of Global.System.Int32)
        Private Partial Sub OnUserIdChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnUserIdChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property TimesheetDate() As Nullable(Of Global.System.DateTime)
            Get
                Return _TimesheetDate
            End Get
            Set
                OnTimesheetDateChanging(value)
                ReportPropertyChanging("TimesheetDate")
                _TimesheetDate = value
                ReportPropertyChanged("TimesheetDate")
                OnTimesheetDateChanged()
            End Set
        End Property
    
        Private _TimesheetDate As Nullable(Of Global.System.DateTime)
        Private Partial Sub OnTimesheetDateChanging(value As Nullable(Of Global.System.DateTime))
        End Sub
    
        Private Partial Sub OnTimesheetDateChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Hours() As Nullable(Of Global.System.Int32)
            Get
                Return _Hours
            End Get
            Set
                OnHoursChanging(value)
                ReportPropertyChanging("Hours")
                _Hours = value
                ReportPropertyChanged("Hours")
                OnHoursChanged()
            End Set
        End Property
    
        Private _Hours As Nullable(Of Global.System.Int32)
        Private Partial Sub OnHoursChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnHoursChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property Minutes() As Nullable(Of Global.System.Int32)
            Get
                Return _Minutes
            End Get
            Set
                OnMinutesChanging(value)
                ReportPropertyChanging("Minutes")
                _Minutes = value
                ReportPropertyChanged("Minutes")
                OnMinutesChanged()
            End Set
        End Property
    
        Private _Minutes As Nullable(Of Global.System.Int32)
        Private Partial Sub OnMinutesChanging(value As Nullable(Of Global.System.Int32))
        End Sub
    
        Private Partial Sub OnMinutesChanged()
        End Sub

        #End Region

    End Class

    #End Region

    
End Namespace
