
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports __User = LightSwitchApplication.User

Namespace LightSwitchApplication

    #Region "Entities"
    
    ''' <summary>
    ''' No Modeled Description Available
    ''' </summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
    Public NotInheritable Partial Class User
        Inherits Global.Microsoft.LightSwitch.Framework.Base.EntityObject(Of __User, __User.DetailsClass)
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new instance of the User entity.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New()
            Me.New(Nothing)
        End Sub
    
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Sub New(entitySet As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __User))
            MyBase.New(entitySet)
            
            __User.DetailsClass.Initialize(Me)
        End Sub
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub User_Created()
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub User_AllowSaveWithErrors(ByRef result As Boolean)
        End Sub
    
        #End Region
    
        #Region "Private Properties"
        
        ''' <summary>
        ''' Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property Application As Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace)
            Get
                Return TryCast(Global.LightSwitchApplication.Application.Current, Global.Microsoft.LightSwitch.IApplication(Of Global.LightSwitchApplication.DataWorkspace))
            End Get
        End Property
        
        ''' <summary>
        ''' Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Private ReadOnly Property DataWorkspace As Global.LightSwitchApplication.DataWorkspace
            Get
                Return DirectCast(Me.Details.EntitySet.Details.DataService.Details.DataWorkspace, Global.LightSwitchApplication.DataWorkspace)
            End Get
        End Property
        
        #End Region
    
        #Region "Public Properties"
    
        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Id As Integer
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Id)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Id, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Id_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property RowVersion As Byte()
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.RowVersion)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.RowVersion, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub RowVersion_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Firstname As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Firstname)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Firstname, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Firstname_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Firstname_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Firstname_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Surname As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Surname)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Surname, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Surname_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Surname_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Surname_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property PhoneNumber As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.PhoneNumber)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.PhoneNumber, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PhoneNumber_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PhoneNumber_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub PhoneNumber_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Username As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Username)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Username, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Username_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Username_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Username_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Password As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Password)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Password, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Password_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Password_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Password_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Address1 As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Address1)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Address1, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address1_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address1_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address1_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Address2 As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Address2)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Address2, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address2_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address2_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Address2_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property City As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.City)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.City, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub City_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Postcode As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Postcode)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Postcode, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Postcode_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Postcode_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Postcode_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Country As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Country)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Country, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Country_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Country_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Country_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Email As String
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Email)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Email, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Email_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Email_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Email_Changed()
        End Sub

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property Issues As Global.Microsoft.LightSwitch.Framework.EntityCollection(Of Global.LightSwitchApplication.Issue)
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Issues)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public ReadOnly Property IssuesQuery As Microsoft.LightSwitch.IDataServiceQueryable(Of Global.LightSwitchApplication.Issue)
            Get
                Return __User.DetailsClass.GetQuery(Me, __User.DetailsClass.PropertySetProperties.Issues)
            End Get
        End Property

        ''' <summary>
        ''' No Modeled Description Available
        ''' </summary>
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public Property Department As Global.LightSwitchApplication.Department
            Get
                Return __User.DetailsClass.GetValue(Me, __User.DetailsClass.PropertySetProperties.Department)
            End Get
            Set
                __User.DetailsClass.SetValue(Me, __User.DetailsClass.PropertySetProperties.Department, Value)
            End Set
        End Property
        
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Department_IsReadOnly(ByRef result As Boolean)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Department_Validate(ByVal results As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
        End Sub
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Private Partial Sub Department_Changed()
        End Sub

        #End Region
    
        #Region "Details Class"
    
        <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
        Public NotInheritable Class DetailsClass
            Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of _
                __User, _
                __User.DetailsClass, _
                __User.DetailsClass.IImplementation, _
                __User.DetailsClass.PropertySet, _
                Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __User, __User.DetailsClass), _
                Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __User, __User.DetailsClass))
    
            Shared Sub New()
                Dim initializeEntry = __User.DetailsClass.PropertySetProperties.Id
            End Sub
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private Shared ReadOnly __UserEntry As Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __User, __User.DetailsClass).Entry = _
                New Global.Microsoft.LightSwitch.Details.Framework.Base.EntityDetails(Of __User, __User.DetailsClass).Entry( _
                    AddressOf __User.DetailsClass.__User_CreateNew, _
                    AddressOf __User.DetailsClass.__User_Created, _
                    AddressOf __User.DetailsClass.__User_AllowSaveWithErrors)
            Private Shared Function __User_CreateNew(es As Global.Microsoft.LightSwitch.Framework.EntitySet(Of __User)) As __User
                Return New __User(es)
            End Function
            Private Shared Sub __User_Created(e As __User)
                e.User_Created()
            End Sub
            Private Shared Function __User_AllowSaveWithErrors(e As __User) As Boolean
                Dim result As Boolean = False
                e.User_AllowSaveWithErrors(result)
                Return result
            End Function
    
            Public Sub New()
                MyBase.New()
            End Sub
    
            Public ReadOnly Shadows Property Commands As Global.Microsoft.LightSwitch.Details.Framework.EntityCommandSet(Of __User, __User.DetailsClass)
                Get
                    Return MyBase.Commands
                End Get
            End Property
    
            Public ReadOnly Shadows Property Methods As Global.Microsoft.LightSwitch.Details.Framework.EntityMethodSet(Of __User, __User.DetailsClass)
                Get
                    Return MyBase.Methods
                End Get
            End Property
    
            Public ReadOnly Shadows Property Properties As __User.DetailsClass.PropertySet
                Get
                    Return MyBase.Properties
                End Get
            End Property
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Public NotInheritable Class PropertySet
                Inherits Global.Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet(Of __User, __User.DetailsClass)
    
                Public Sub New()
                    MyBase.New()
                End Sub
    
                Public ReadOnly Property Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Id),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer))
                    End Get
                End Property
                
                Public ReadOnly Property RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Byte())
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.RowVersion),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Byte()))
                    End Get
                End Property
                
                Public ReadOnly Property Firstname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Firstname),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Surname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Surname),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property PhoneNumber As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.PhoneNumber),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Username As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Username),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Password As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Password),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Address1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Address1),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Address2 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Address2),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.City),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Postcode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Postcode),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Country As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Country),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Email As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Email),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String))
                    End Get
                End Property
                
                Public ReadOnly Property Issues As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Issue)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Issues),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Issue))
                    End Get
                End Property
                
                Public ReadOnly Property Department As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Department)
                    Get
                        Return TryCast(
                            MyBase.GetItem(__User.DetailsClass.PropertySetProperties.Department),
                            Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Department))
                    End Get
                End Property
                
            End Class
    
            <Global.System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")> _
            Public Interface IImplementation
                Inherits Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
                Shadows Property Id As Integer
                Shadows Property RowVersion As Byte()
                Shadows Property Firstname As String
                Shadows Property Surname As String
                Shadows Property PhoneNumber As String
                Shadows Property Username As String
                Shadows Property Password As String
                Shadows Property Address1 As String
                Shadows Property Address2 As String
                Shadows Property City As String
                Shadows Property Postcode As String
                Shadows Property Country As String
                Shadows Property Email As String
                Shadows ReadOnly Property Issues As Global.System.Collections.IEnumerable
                Shadows Property Department As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
    
            End Interface
    
            <Global.System.ComponentModel.EditorBrowsable(Global.System.ComponentModel.EditorBrowsableState.Never)> _
            <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")> _
            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
            Friend Class PropertySetProperties
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer).Entry( _
                        "Id", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Id_OnValueChanged)
                Private Shared Sub _Id_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Id, sf)
                End Sub
                Private Shared Function _Id_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Id_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Id_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Id_Validate(r)
                End Sub
                Private Shared Function _Id_GetImplementationValue(d As __User.DetailsClass) As Integer
                    Return d.ImplementationEntity.Id
                End Function
                Private Shared Sub _Id_SetImplementationValue(d As __User.DetailsClass, v As Integer)
                    d.ImplementationEntity.Id = v
                End Sub
                Private Shared Sub _Id_OnValueChanged(e As __User)
                    e.Id_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Byte()).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Byte()).Entry( _
                        "RowVersion", _
                        AddressOf __User.DetailsClass.PropertySetProperties._RowVersion_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._RowVersion_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged)
                Private Shared Sub _RowVersion_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Byte()).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._RowVersion, sf)
                End Sub
                Private Shared Function _RowVersion_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.RowVersion_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _RowVersion_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.RowVersion_Validate(r)
                End Sub
                Private Shared Function _RowVersion_GetImplementationValue(d As __User.DetailsClass) As Byte()
                    Return d.ImplementationEntity.RowVersion
                End Function
                Private Shared Sub _RowVersion_SetImplementationValue(d As __User.DetailsClass, v As Byte())
                    d.ImplementationEntity.RowVersion = v
                End Sub
                Private Shared Sub _RowVersion_OnValueChanged(e As __User)
                    e.RowVersion_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Firstname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Firstname", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Firstname_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Firstname_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Firstname_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Firstname_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Firstname_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Firstname_OnValueChanged)
                Private Shared Sub _Firstname_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Firstname, sf)
                End Sub
                Private Shared Function _Firstname_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Firstname_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Firstname_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Firstname_Validate(r)
                End Sub
                Private Shared Function _Firstname_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Firstname
                End Function
                Private Shared Sub _Firstname_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Firstname = v
                End Sub
                Private Shared Sub _Firstname_OnValueChanged(e As __User)
                    e.Firstname_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Surname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Surname", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Surname_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Surname_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Surname_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Surname_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Surname_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Surname_OnValueChanged)
                Private Shared Sub _Surname_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Surname, sf)
                End Sub
                Private Shared Function _Surname_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Surname_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Surname_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Surname_Validate(r)
                End Sub
                Private Shared Function _Surname_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Surname
                End Function
                Private Shared Sub _Surname_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Surname = v
                End Sub
                Private Shared Sub _Surname_OnValueChanged(e As __User)
                    e.Surname_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly PhoneNumber As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "PhoneNumber", _
                        AddressOf __User.DetailsClass.PropertySetProperties._PhoneNumber_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._PhoneNumber_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._PhoneNumber_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._PhoneNumber_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._PhoneNumber_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._PhoneNumber_OnValueChanged)
                Private Shared Sub _PhoneNumber_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._PhoneNumber, sf)
                End Sub
                Private Shared Function _PhoneNumber_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.PhoneNumber_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _PhoneNumber_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.PhoneNumber_Validate(r)
                End Sub
                Private Shared Function _PhoneNumber_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.PhoneNumber
                End Function
                Private Shared Sub _PhoneNumber_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.PhoneNumber = v
                End Sub
                Private Shared Sub _PhoneNumber_OnValueChanged(e As __User)
                    e.PhoneNumber_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Username As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Username", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Username_OnValueChanged)
                Private Shared Sub _Username_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Username, sf)
                End Sub
                Private Shared Function _Username_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Username_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Username_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Username_Validate(r)
                End Sub
                Private Shared Function _Username_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Username
                End Function
                Private Shared Sub _Username_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Username = v
                End Sub
                Private Shared Sub _Username_OnValueChanged(e As __User)
                    e.Username_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Password As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Password", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Password_OnValueChanged)
                Private Shared Sub _Password_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Password, sf)
                End Sub
                Private Shared Function _Password_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Password_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Password_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Password_Validate(r)
                End Sub
                Private Shared Function _Password_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Password
                End Function
                Private Shared Sub _Password_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Password = v
                End Sub
                Private Shared Sub _Password_OnValueChanged(e As __User)
                    e.Password_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Address1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Address1", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address1_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address1_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address1_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address1_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address1_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address1_OnValueChanged)
                Private Shared Sub _Address1_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Address1, sf)
                End Sub
                Private Shared Function _Address1_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Address1_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Address1_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Address1_Validate(r)
                End Sub
                Private Shared Function _Address1_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Address1
                End Function
                Private Shared Sub _Address1_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Address1 = v
                End Sub
                Private Shared Sub _Address1_OnValueChanged(e As __User)
                    e.Address1_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Address2 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Address2", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address2_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address2_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address2_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address2_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address2_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Address2_OnValueChanged)
                Private Shared Sub _Address2_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Address2, sf)
                End Sub
                Private Shared Function _Address2_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Address2_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Address2_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Address2_Validate(r)
                End Sub
                Private Shared Function _Address2_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Address2
                End Function
                Private Shared Sub _Address2_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Address2 = v
                End Sub
                Private Shared Sub _Address2_OnValueChanged(e As __User)
                    e.Address2_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "City", _
                        AddressOf __User.DetailsClass.PropertySetProperties._City_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._City_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._City_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._City_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._City_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._City_OnValueChanged)
                Private Shared Sub _City_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._City, sf)
                End Sub
                Private Shared Function _City_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.City_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _City_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.City_Validate(r)
                End Sub
                Private Shared Function _City_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.City
                End Function
                Private Shared Sub _City_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.City = v
                End Sub
                Private Shared Sub _City_OnValueChanged(e As __User)
                    e.City_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Postcode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Postcode", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Postcode_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Postcode_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Postcode_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Postcode_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Postcode_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Postcode_OnValueChanged)
                Private Shared Sub _Postcode_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Postcode, sf)
                End Sub
                Private Shared Function _Postcode_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Postcode_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Postcode_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Postcode_Validate(r)
                End Sub
                Private Shared Function _Postcode_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Postcode
                End Function
                Private Shared Sub _Postcode_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Postcode = v
                End Sub
                Private Shared Sub _Postcode_OnValueChanged(e As __User)
                    e.Postcode_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Country As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Country", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Country_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Country_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Country_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Country_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Country_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Country_OnValueChanged)
                Private Shared Sub _Country_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Country, sf)
                End Sub
                Private Shared Function _Country_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Country_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Country_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Country_Validate(r)
                End Sub
                Private Shared Function _Country_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Country
                End Function
                Private Shared Sub _Country_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Country = v
                End Sub
                Private Shared Sub _Country_OnValueChanged(e As __User)
                    e.Country_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Email As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Entry( _
                        "Email", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Email_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Email_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Email_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Email_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Email_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Email_OnValueChanged)
                Private Shared Sub _Email_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Email, sf)
                End Sub
                Private Shared Function _Email_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Email_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Email_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Email_Validate(r)
                End Sub
                Private Shared Function _Email_GetImplementationValue(d As __User.DetailsClass) As String
                    Return d.ImplementationEntity.Email
                End Function
                Private Shared Sub _Email_SetImplementationValue(d As __User.DetailsClass, v As String)
                    d.ImplementationEntity.Email = v
                End Sub
                Private Shared Sub _Email_OnValueChanged(e As __User)
                    e.Email_Changed()
                End Sub
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Issues As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Issue).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Issue).Entry( _
                        "Issues", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Issues_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Issues_GetReferencedEntities, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Issues_GetEntityCollection)
                Private Shared Sub _Issues_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Issue).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Issues, sf)
                End Sub
                Private Shared Function _Issues_GetReferencedEntities(d As __User.DetailsClass) As Global.System.Collections.Generic.IEnumerable(Of Global.LightSwitchApplication.Issue)
                    Return d.GetReferencedEntities(Of Global.LightSwitchApplication.Issue, Global.LightSwitchApplication.Issue.DetailsClass)(__User.DetailsClass.PropertySetProperties.Issues, d._Issues)
                End Function
                Private Shared Function _Issues_GetEntityCollection(d As __User.DetailsClass) As Global.System.Collections.IEnumerable
                    Return d.ImplementationEntity.Issues
                End Function
    
                <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
                Public Shared ReadOnly Department As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Department).Entry = _
                    New Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Department).Entry( _
                        "Department", _
                        AddressOf __User.DetailsClass.PropertySetProperties._Department_Stub, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Department_ComputeIsReadOnly, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Department_Validate, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Department_GetCoreImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Department_GetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Department_SetImplementationValue, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Department_Refresh, _
                        AddressOf __User.DetailsClass.PropertySetProperties._Department_OnValueChanged)
                Private Shared Sub _Department_Stub(c As Global.Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback(Of __User.DetailsClass, Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Department).Data), d As __User.DetailsClass, sf As Object)
                    c(d, d._Department, sf)
                End Sub
                Private Shared Function _Department_ComputeIsReadOnly(e As __User) As Boolean
                    Dim result As Boolean = False
                    e.Department_IsReadOnly(result)
                    Return result
                End Function
                Private Shared Sub _Department_Validate(e As __User, r As Global.Microsoft.LightSwitch.EntityValidationResultsBuilder)
                    e.Department_Validate(r)
                End Sub
                Private Shared Function _Department_GetCoreImplementationValue(d as __User.DetailsClass) As Global.Microsoft.LightSwitch.Internal.IEntityImplementation
                    Return d.ImplementationEntity.Department
                End Function
                Private Shared Function _Department_GetImplementationValue(d as __User.DetailsClass) As Global.LightSwitchApplication.Department
                    Return d.GetImplementationValue(Of Global.LightSwitchApplication.Department, Global.LightSwitchApplication.Department.DetailsClass)(__User.DetailsClass.PropertySetProperties.Department, d._Department)
                End Function
                Private Shared Sub _Department_SetImplementationValue(d As __User.DetailsClass, v As Global.LightSwitchApplication.Department)
                    d.SetImplementationValue(__User.DetailsClass.PropertySetProperties.Department, d._Department, Sub(i, ev) i.Department = ev, v)
                End Sub
                Private Shared Sub _Department_Refresh(d As __User.DetailsClass)
                    d.RefreshNavigationProperty(__User.DetailsClass.PropertySetProperties.Department, d._Department)
                End Sub
                Private Shared Sub _Department_OnValueChanged(e As __User)
                    e.Department_Changed()
                End Sub
    
            End Class
    
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Id As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Integer).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _RowVersion As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, Byte()).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Firstname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Surname As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _PhoneNumber As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Username As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Password As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Address1 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Address2 As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _City As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Postcode As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Country As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Email As Global.Microsoft.LightSwitch.Details.Framework.EntityStorageProperty(Of __User, __User.DetailsClass, String).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Issues As Global.Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Issue).Data
            
            <Global.System.Diagnostics.DebuggerBrowsable(Global.System.Diagnostics.DebuggerBrowsableState.Never)> _
            Private _Department As Global.Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty(Of __User, __User.DetailsClass, Global.LightSwitchApplication.Department).Data
            
        End Class
    
        #End Region
    
    End Class
    
    #End Region
End Namespace
