

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class EmailOperation : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EmailOperation entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EmailOperation()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EmailOperation(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EmailOperation> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EmailOperation.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailOperation_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailOperation_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.EmailOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.EmailOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.EmailOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.EmailOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SenderEmail
        {
            get
            {
                return global::LightSwitchApplication.EmailOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.SenderEmail);
            }
            set
            {
                global::LightSwitchApplication.EmailOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.SenderEmail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SenderEmail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SenderEmail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SenderEmail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RecipientEmail
        {
            get
            {
                return global::LightSwitchApplication.EmailOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.RecipientEmail);
            }
            set
            {
                global::LightSwitchApplication.EmailOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.RecipientEmail, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RecipientEmail_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RecipientEmail_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RecipientEmail_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Subject
        {
            get
            {
                return global::LightSwitchApplication.EmailOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Subject);
            }
            set
            {
                global::LightSwitchApplication.EmailOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Subject, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Body
        {
            get
            {
                return global::LightSwitchApplication.EmailOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Body);
            }
            set
            {
                global::LightSwitchApplication.EmailOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Body, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] Attachment
        {
            get
            {
                return global::LightSwitchApplication.EmailOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Attachment);
            }
            set
            {
                global::LightSwitchApplication.EmailOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Attachment, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Attachment_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Attachment_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Attachment_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string AttachmentFileName
        {
            get
            {
                return global::LightSwitchApplication.EmailOperation.DetailsClass.GetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.AttachmentFileName);
            }
            set
            {
                global::LightSwitchApplication.EmailOperation.DetailsClass.SetValue(this, global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.AttachmentFileName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AttachmentFileName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AttachmentFileName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AttachmentFileName_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EmailOperation,
                global::LightSwitchApplication.EmailOperation.DetailsClass,
                global::LightSwitchApplication.EmailOperation.DetailsClass.IImplementation,
                global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass>.Entry
                __EmailOperationEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass>.Entry(
                    global::LightSwitchApplication.EmailOperation.DetailsClass.__EmailOperation_CreateNew,
                    global::LightSwitchApplication.EmailOperation.DetailsClass.__EmailOperation_Created,
                    global::LightSwitchApplication.EmailOperation.DetailsClass.__EmailOperation_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EmailOperation __EmailOperation_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EmailOperation> es)
            {
                return new global::LightSwitchApplication.EmailOperation(es);
            }
            private static void __EmailOperation_Created(global::LightSwitchApplication.EmailOperation e)
            {
                e.EmailOperation_Created();
            }
            private static bool __EmailOperation_AllowSaveWithErrors(global::LightSwitchApplication.EmailOperation e)
            {
                bool result = false;
                e.EmailOperation_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string> SenderEmail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.SenderEmail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string> RecipientEmail
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.RecipientEmail) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string> Subject
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Subject) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string> Body
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Body) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]> Attachment
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.Attachment) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string> AttachmentFileName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties.AttachmentFileName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string SenderEmail { get; set; }
                new string RecipientEmail { get; set; }
                new string Subject { get; set; }
                new string Body { get; set; }
                new byte[] Attachment { get; set; }
                new string AttachmentFileName { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmailOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, int>.Data> c, global::LightSwitchApplication.EmailOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.EmailOperation e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.EmailOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.EmailOperation e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmailOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.EmailOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.EmailOperation e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.EmailOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.EmailOperation e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry
                    SenderEmail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry(
                        "SenderEmail",
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._SenderEmail_Stub,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._SenderEmail_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._SenderEmail_Validate,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._SenderEmail_GetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._SenderEmail_SetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._SenderEmail_OnValueChanged);
                private static void _SenderEmail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmailOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmailOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._SenderEmail, sf);
                }
                private static bool _SenderEmail_ComputeIsReadOnly(global::LightSwitchApplication.EmailOperation e)
                {
                    bool result = false;
                    e.SenderEmail_IsReadOnly(ref result);
                    return result;
                }
                private static void _SenderEmail_Validate(global::LightSwitchApplication.EmailOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SenderEmail_Validate(r);
                }
                private static string _SenderEmail_GetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.SenderEmail;
                }
                private static void _SenderEmail_SetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SenderEmail = v;
                }
                private static void _SenderEmail_OnValueChanged(global::LightSwitchApplication.EmailOperation e)
                {
                    e.SenderEmail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry
                    RecipientEmail = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry(
                        "RecipientEmail",
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RecipientEmail_Stub,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RecipientEmail_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RecipientEmail_Validate,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RecipientEmail_GetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RecipientEmail_SetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._RecipientEmail_OnValueChanged);
                private static void _RecipientEmail_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmailOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmailOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._RecipientEmail, sf);
                }
                private static bool _RecipientEmail_ComputeIsReadOnly(global::LightSwitchApplication.EmailOperation e)
                {
                    bool result = false;
                    e.RecipientEmail_IsReadOnly(ref result);
                    return result;
                }
                private static void _RecipientEmail_Validate(global::LightSwitchApplication.EmailOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RecipientEmail_Validate(r);
                }
                private static string _RecipientEmail_GetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.RecipientEmail;
                }
                private static void _RecipientEmail_SetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RecipientEmail = v;
                }
                private static void _RecipientEmail_OnValueChanged(global::LightSwitchApplication.EmailOperation e)
                {
                    e.RecipientEmail_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry
                    Subject = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry(
                        "Subject",
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Subject_Stub,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Subject_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Subject_Validate,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Subject_GetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Subject_SetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Subject_OnValueChanged);
                private static void _Subject_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmailOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmailOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._Subject, sf);
                }
                private static bool _Subject_ComputeIsReadOnly(global::LightSwitchApplication.EmailOperation e)
                {
                    bool result = false;
                    e.Subject_IsReadOnly(ref result);
                    return result;
                }
                private static void _Subject_Validate(global::LightSwitchApplication.EmailOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Subject_Validate(r);
                }
                private static string _Subject_GetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.Subject;
                }
                private static void _Subject_SetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Subject = v;
                }
                private static void _Subject_OnValueChanged(global::LightSwitchApplication.EmailOperation e)
                {
                    e.Subject_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry
                    Body = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry(
                        "Body",
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Body_Stub,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Body_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Body_Validate,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Body_GetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Body_SetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Body_OnValueChanged);
                private static void _Body_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmailOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmailOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._Body, sf);
                }
                private static bool _Body_ComputeIsReadOnly(global::LightSwitchApplication.EmailOperation e)
                {
                    bool result = false;
                    e.Body_IsReadOnly(ref result);
                    return result;
                }
                private static void _Body_Validate(global::LightSwitchApplication.EmailOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Body_Validate(r);
                }
                private static string _Body_GetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.Body;
                }
                private static void _Body_SetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Body = v;
                }
                private static void _Body_OnValueChanged(global::LightSwitchApplication.EmailOperation e)
                {
                    e.Body_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>.Entry
                    Attachment = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>.Entry(
                        "Attachment",
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Attachment_Stub,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Attachment_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Attachment_Validate,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Attachment_GetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Attachment_SetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._Attachment_OnValueChanged);
                private static void _Attachment_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmailOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.EmailOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._Attachment, sf);
                }
                private static bool _Attachment_ComputeIsReadOnly(global::LightSwitchApplication.EmailOperation e)
                {
                    bool result = false;
                    e.Attachment_IsReadOnly(ref result);
                    return result;
                }
                private static void _Attachment_Validate(global::LightSwitchApplication.EmailOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Attachment_Validate(r);
                }
                private static byte[] _Attachment_GetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.Attachment;
                }
                private static void _Attachment_SetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.Attachment = v;
                }
                private static void _Attachment_OnValueChanged(global::LightSwitchApplication.EmailOperation e)
                {
                    e.Attachment_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry
                    AttachmentFileName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Entry(
                        "AttachmentFileName",
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._AttachmentFileName_Stub,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._AttachmentFileName_ComputeIsReadOnly,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._AttachmentFileName_Validate,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._AttachmentFileName_GetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._AttachmentFileName_SetImplementationValue,
                        global::LightSwitchApplication.EmailOperation.DetailsClass.PropertySetProperties._AttachmentFileName_OnValueChanged);
                private static void _AttachmentFileName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EmailOperation.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data> c, global::LightSwitchApplication.EmailOperation.DetailsClass d, object sf)
                {
                    c(d, ref d._AttachmentFileName, sf);
                }
                private static bool _AttachmentFileName_ComputeIsReadOnly(global::LightSwitchApplication.EmailOperation e)
                {
                    bool result = false;
                    e.AttachmentFileName_IsReadOnly(ref result);
                    return result;
                }
                private static void _AttachmentFileName_Validate(global::LightSwitchApplication.EmailOperation e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.AttachmentFileName_Validate(r);
                }
                private static string _AttachmentFileName_GetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d)
                {
                    return d.ImplementationEntity.AttachmentFileName;
                }
                private static void _AttachmentFileName_SetImplementationValue(global::LightSwitchApplication.EmailOperation.DetailsClass d, string v)
                {
                    d.ImplementationEntity.AttachmentFileName = v;
                }
                private static void _AttachmentFileName_OnValueChanged(global::LightSwitchApplication.EmailOperation e)
                {
                    e.AttachmentFileName_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data _SenderEmail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data _RecipientEmail;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data _Subject;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data _Body;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, byte[]>.Data _Attachment;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EmailOperation, global::LightSwitchApplication.EmailOperation.DetailsClass, string>.Data _AttachmentFileName;
            
        }
    
        #endregion
    }
    
    #endregion
}
