

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Department : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Department entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Department()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Department(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Department> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Department.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Department_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Department_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DepartmentName
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.DepartmentName);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.DepartmentName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DepartmentName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DepartmentName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DepartmentName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Address1
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Address1);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Address1, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address1_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address1_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address1_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Address2
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Address2);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Address2, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address2_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address2_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Address2_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string City
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.City);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.City, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void City_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void City_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void City_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Postcode
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Postcode);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Postcode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postcode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postcode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Postcode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Country
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Country);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Country, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Country_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Country_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Country_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DepartmentManager
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.DepartmentManager);
            }
            set
            {
                global::LightSwitchApplication.Department.DetailsClass.SetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.DepartmentManager, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DepartmentManager_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DepartmentManager_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DepartmentManager_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.User> Users
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetValue(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Users);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.User> UsersQuery
        {
            get
            {
                return global::LightSwitchApplication.Department.DetailsClass.GetQuery(this, global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Users);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Department,
                global::LightSwitchApplication.Department.DetailsClass,
                global::LightSwitchApplication.Department.DetailsClass.IImplementation,
                global::LightSwitchApplication.Department.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass>.Entry
                __DepartmentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass>.Entry(
                    global::LightSwitchApplication.Department.DetailsClass.__Department_CreateNew,
                    global::LightSwitchApplication.Department.DetailsClass.__Department_Created,
                    global::LightSwitchApplication.Department.DetailsClass.__Department_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Department __Department_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Department> es)
            {
                return new global::LightSwitchApplication.Department(es);
            }
            private static void __Department_Created(global::LightSwitchApplication.Department e)
            {
                e.Department_Created();
            }
            private static bool __Department_AllowSaveWithErrors(global::LightSwitchApplication.Department e)
            {
                bool result = false;
                e.Department_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Department.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string> DepartmentName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.DepartmentName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string> Address1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Address1) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string> Address2
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Address2) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string> City
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.City) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string> Postcode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Postcode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string> Country
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Country) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string> DepartmentManager
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.DepartmentManager) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, global::LightSwitchApplication.User> Users
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Users) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, global::LightSwitchApplication.User>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string DepartmentName { get; set; }
                new string Address1 { get; set; }
                new string Address2 { get; set; }
                new string City { get; set; }
                new string Postcode { get; set; }
                new string Country { get; set; }
                new string DepartmentManager { get; set; }
                new global::System.Collections.IEnumerable Users { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, int>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry
                    DepartmentName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry(
                        "DepartmentName",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentName_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentName_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentName_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentName_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentName_OnValueChanged);
                private static void _DepartmentName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._DepartmentName, sf);
                }
                private static bool _DepartmentName_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.DepartmentName_IsReadOnly(ref result);
                    return result;
                }
                private static void _DepartmentName_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DepartmentName_Validate(r);
                }
                private static string _DepartmentName_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.DepartmentName;
                }
                private static void _DepartmentName_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DepartmentName = v;
                }
                private static void _DepartmentName_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.DepartmentName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry
                    Address1 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry(
                        "Address1",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address1_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address1_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address1_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address1_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address1_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address1_OnValueChanged);
                private static void _Address1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._Address1, sf);
                }
                private static bool _Address1_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.Address1_IsReadOnly(ref result);
                    return result;
                }
                private static void _Address1_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Address1_Validate(r);
                }
                private static string _Address1_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.Address1;
                }
                private static void _Address1_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Address1 = v;
                }
                private static void _Address1_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.Address1_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry
                    Address2 = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry(
                        "Address2",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address2_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address2_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address2_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address2_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address2_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Address2_OnValueChanged);
                private static void _Address2_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._Address2, sf);
                }
                private static bool _Address2_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.Address2_IsReadOnly(ref result);
                    return result;
                }
                private static void _Address2_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Address2_Validate(r);
                }
                private static string _Address2_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.Address2;
                }
                private static void _Address2_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Address2 = v;
                }
                private static void _Address2_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.Address2_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry
                    City = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry(
                        "City",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._City_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._City_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._City_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._City_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._City_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._City_OnValueChanged);
                private static void _City_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._City, sf);
                }
                private static bool _City_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.City_IsReadOnly(ref result);
                    return result;
                }
                private static void _City_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.City_Validate(r);
                }
                private static string _City_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.City;
                }
                private static void _City_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, string v)
                {
                    d.ImplementationEntity.City = v;
                }
                private static void _City_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.City_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry
                    Postcode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry(
                        "Postcode",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Postcode_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Postcode_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Postcode_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Postcode_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Postcode_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Postcode_OnValueChanged);
                private static void _Postcode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._Postcode, sf);
                }
                private static bool _Postcode_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.Postcode_IsReadOnly(ref result);
                    return result;
                }
                private static void _Postcode_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Postcode_Validate(r);
                }
                private static string _Postcode_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.Postcode;
                }
                private static void _Postcode_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Postcode = v;
                }
                private static void _Postcode_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.Postcode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry
                    Country = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry(
                        "Country",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Country_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Country_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Country_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Country_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Country_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Country_OnValueChanged);
                private static void _Country_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._Country, sf);
                }
                private static bool _Country_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.Country_IsReadOnly(ref result);
                    return result;
                }
                private static void _Country_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Country_Validate(r);
                }
                private static string _Country_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.Country;
                }
                private static void _Country_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Country = v;
                }
                private static void _Country_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.Country_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry
                    DepartmentManager = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Entry(
                        "DepartmentManager",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentManager_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentManager_ComputeIsReadOnly,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentManager_Validate,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentManager_GetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentManager_SetImplementationValue,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._DepartmentManager_OnValueChanged);
                private static void _DepartmentManager_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._DepartmentManager, sf);
                }
                private static bool _DepartmentManager_ComputeIsReadOnly(global::LightSwitchApplication.Department e)
                {
                    bool result = false;
                    e.DepartmentManager_IsReadOnly(ref result);
                    return result;
                }
                private static void _DepartmentManager_Validate(global::LightSwitchApplication.Department e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DepartmentManager_Validate(r);
                }
                private static string _DepartmentManager_GetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.DepartmentManager;
                }
                private static void _DepartmentManager_SetImplementationValue(global::LightSwitchApplication.Department.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DepartmentManager = v;
                }
                private static void _DepartmentManager_OnValueChanged(global::LightSwitchApplication.Department e)
                {
                    e.DepartmentManager_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, global::LightSwitchApplication.User>.Entry
                    Users = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, global::LightSwitchApplication.User>.Entry(
                        "Users",
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Users_Stub,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Users_GetReferencedEntities,
                        global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties._Users_GetEntityCollection);
                private static void _Users_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Department.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, global::LightSwitchApplication.User>.Data> c, global::LightSwitchApplication.Department.DetailsClass d, object sf)
                {
                    c(d, ref d._Users, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.User> _Users_GetReferencedEntities(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.User, global::LightSwitchApplication.User.DetailsClass>(global::LightSwitchApplication.Department.DetailsClass.PropertySetProperties.Users, ref d._Users);
                }
                private static global::System.Collections.IEnumerable _Users_GetEntityCollection(global::LightSwitchApplication.Department.DetailsClass d)
                {
                    return d.ImplementationEntity.Users;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data _DepartmentName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data _Address1;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data _Address2;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data _City;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data _Postcode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data _Country;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, string>.Data _DepartmentManager;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Department, global::LightSwitchApplication.Department.DetailsClass, global::LightSwitchApplication.User>.Data _Users;
            
        }
    
        #endregion
    }
    
    #endregion
}
