

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Skill : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Skill entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Skill()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Skill(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Skill> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Skill.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Skill_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Skill_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Skill.DetailsClass.GetValue(this, global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Skill.DetailsClass.SetValue(this, global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.Skill.DetailsClass.GetValue(this, global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.Skill.DetailsClass.SetValue(this, global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SkillDescription
        {
            get
            {
                return global::LightSwitchApplication.Skill.DetailsClass.GetValue(this, global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.SkillDescription);
            }
            set
            {
                global::LightSwitchApplication.Skill.DetailsClass.SetValue(this, global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.SkillDescription, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkillDescription_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkillDescription_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SkillDescription_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.EngineerSkill> EngineerSkills
        {
            get
            {
                return global::LightSwitchApplication.Skill.DetailsClass.GetValue(this, global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.EngineerSkills);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.EngineerSkill> EngineerSkillsQuery
        {
            get
            {
                return global::LightSwitchApplication.Skill.DetailsClass.GetQuery(this, global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.EngineerSkills);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Skill,
                global::LightSwitchApplication.Skill.DetailsClass,
                global::LightSwitchApplication.Skill.DetailsClass.IImplementation,
                global::LightSwitchApplication.Skill.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass>.Entry
                __SkillEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass>.Entry(
                    global::LightSwitchApplication.Skill.DetailsClass.__Skill_CreateNew,
                    global::LightSwitchApplication.Skill.DetailsClass.__Skill_Created,
                    global::LightSwitchApplication.Skill.DetailsClass.__Skill_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Skill __Skill_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Skill> es)
            {
                return new global::LightSwitchApplication.Skill(es);
            }
            private static void __Skill_Created(global::LightSwitchApplication.Skill e)
            {
                e.Skill_Created();
            }
            private static bool __Skill_AllowSaveWithErrors(global::LightSwitchApplication.Skill e)
            {
                bool result = false;
                e.Skill_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Skill.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, string> SkillDescription
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.SkillDescription) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, global::LightSwitchApplication.EngineerSkill> EngineerSkills
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.EngineerSkills) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, global::LightSwitchApplication.EngineerSkill>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string SkillDescription { get; set; }
                new global::System.Collections.IEnumerable EngineerSkills { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Skill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, int>.Data> c, global::LightSwitchApplication.Skill.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Skill e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Skill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Skill.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Skill.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Skill e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Skill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.Skill.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.Skill e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.Skill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.Skill.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.Skill.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.Skill e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, string>.Entry
                    SkillDescription = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, string>.Entry(
                        "SkillDescription",
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._SkillDescription_Stub,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._SkillDescription_ComputeIsReadOnly,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._SkillDescription_Validate,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._SkillDescription_GetImplementationValue,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._SkillDescription_SetImplementationValue,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._SkillDescription_OnValueChanged);
                private static void _SkillDescription_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Skill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, string>.Data> c, global::LightSwitchApplication.Skill.DetailsClass d, object sf)
                {
                    c(d, ref d._SkillDescription, sf);
                }
                private static bool _SkillDescription_ComputeIsReadOnly(global::LightSwitchApplication.Skill e)
                {
                    bool result = false;
                    e.SkillDescription_IsReadOnly(ref result);
                    return result;
                }
                private static void _SkillDescription_Validate(global::LightSwitchApplication.Skill e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SkillDescription_Validate(r);
                }
                private static string _SkillDescription_GetImplementationValue(global::LightSwitchApplication.Skill.DetailsClass d)
                {
                    return d.ImplementationEntity.SkillDescription;
                }
                private static void _SkillDescription_SetImplementationValue(global::LightSwitchApplication.Skill.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SkillDescription = v;
                }
                private static void _SkillDescription_OnValueChanged(global::LightSwitchApplication.Skill e)
                {
                    e.SkillDescription_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, global::LightSwitchApplication.EngineerSkill>.Entry
                    EngineerSkills = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, global::LightSwitchApplication.EngineerSkill>.Entry(
                        "EngineerSkills",
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._EngineerSkills_Stub,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._EngineerSkills_GetReferencedEntities,
                        global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties._EngineerSkills_GetEntityCollection);
                private static void _EngineerSkills_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Skill.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, global::LightSwitchApplication.EngineerSkill>.Data> c, global::LightSwitchApplication.Skill.DetailsClass d, object sf)
                {
                    c(d, ref d._EngineerSkills, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.EngineerSkill> _EngineerSkills_GetReferencedEntities(global::LightSwitchApplication.Skill.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.EngineerSkill, global::LightSwitchApplication.EngineerSkill.DetailsClass>(global::LightSwitchApplication.Skill.DetailsClass.PropertySetProperties.EngineerSkills, ref d._EngineerSkills);
                }
                private static global::System.Collections.IEnumerable _EngineerSkills_GetEntityCollection(global::LightSwitchApplication.Skill.DetailsClass d)
                {
                    return d.ImplementationEntity.EngineerSkills;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, string>.Data _SkillDescription;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Skill, global::LightSwitchApplication.Skill.DetailsClass, global::LightSwitchApplication.EngineerSkill>.Data _EngineerSkills;
            
        }
    
        #endregion
    }
    
    #endregion
}
