

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class IssueDocument : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the IssueDocument entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public IssueDocument()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public IssueDocument(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.IssueDocument> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.IssueDocument.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IssueDocument_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IssueDocument_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.IssueDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.IssueDocument.DetailsClass.SetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.IssueDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.IssueDocument.DetailsClass.SetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DocumentName
        {
            get
            {
                return global::LightSwitchApplication.IssueDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.DocumentName);
            }
            set
            {
                global::LightSwitchApplication.IssueDocument.DetailsClass.SetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.DocumentName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DocumentName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string FileExtension
        {
            get
            {
                return global::LightSwitchApplication.IssueDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.FileExtension);
            }
            set
            {
                global::LightSwitchApplication.IssueDocument.DetailsClass.SetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.FileExtension, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FileExtension_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FileExtension_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void FileExtension_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] IssueFile
        {
            get
            {
                return global::LightSwitchApplication.IssueDocument.DetailsClass.GetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.IssueFile);
            }
            set
            {
                global::LightSwitchApplication.IssueDocument.DetailsClass.SetValue(this, global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.IssueFile, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IssueFile_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IssueFile_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IssueFile_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.IssueDocument,
                global::LightSwitchApplication.IssueDocument.DetailsClass,
                global::LightSwitchApplication.IssueDocument.DetailsClass.IImplementation,
                global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass>.Entry
                __IssueDocumentEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass>.Entry(
                    global::LightSwitchApplication.IssueDocument.DetailsClass.__IssueDocument_CreateNew,
                    global::LightSwitchApplication.IssueDocument.DetailsClass.__IssueDocument_Created,
                    global::LightSwitchApplication.IssueDocument.DetailsClass.__IssueDocument_AllowSaveWithErrors);
            private static global::LightSwitchApplication.IssueDocument __IssueDocument_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.IssueDocument> es)
            {
                return new global::LightSwitchApplication.IssueDocument(es);
            }
            private static void __IssueDocument_Created(global::LightSwitchApplication.IssueDocument e)
            {
                e.IssueDocument_Created();
            }
            private static bool __IssueDocument_AllowSaveWithErrors(global::LightSwitchApplication.IssueDocument e)
            {
                bool result = false;
                e.IssueDocument_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string> DocumentName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.DocumentName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string> FileExtension
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.FileExtension) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]> IssueFile
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties.IssueFile) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string DocumentName { get; set; }
                new string FileExtension { get; set; }
                new byte[] IssueFile { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IssueDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, int>.Data> c, global::LightSwitchApplication.IssueDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.IssueDocument e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.IssueDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.IssueDocument e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IssueDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.IssueDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.IssueDocument e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.IssueDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.IssueDocument e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>.Entry
                    DocumentName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>.Entry(
                        "DocumentName",
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._DocumentName_Stub,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._DocumentName_ComputeIsReadOnly,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._DocumentName_Validate,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._DocumentName_GetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._DocumentName_SetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._DocumentName_OnValueChanged);
                private static void _DocumentName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IssueDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>.Data> c, global::LightSwitchApplication.IssueDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._DocumentName, sf);
                }
                private static bool _DocumentName_ComputeIsReadOnly(global::LightSwitchApplication.IssueDocument e)
                {
                    bool result = false;
                    e.DocumentName_IsReadOnly(ref result);
                    return result;
                }
                private static void _DocumentName_Validate(global::LightSwitchApplication.IssueDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DocumentName_Validate(r);
                }
                private static string _DocumentName_GetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.DocumentName;
                }
                private static void _DocumentName_SetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DocumentName = v;
                }
                private static void _DocumentName_OnValueChanged(global::LightSwitchApplication.IssueDocument e)
                {
                    e.DocumentName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>.Entry
                    FileExtension = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>.Entry(
                        "FileExtension",
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._FileExtension_Stub,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._FileExtension_ComputeIsReadOnly,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._FileExtension_Validate,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._FileExtension_GetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._FileExtension_SetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._FileExtension_OnValueChanged);
                private static void _FileExtension_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IssueDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>.Data> c, global::LightSwitchApplication.IssueDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._FileExtension, sf);
                }
                private static bool _FileExtension_ComputeIsReadOnly(global::LightSwitchApplication.IssueDocument e)
                {
                    bool result = false;
                    e.FileExtension_IsReadOnly(ref result);
                    return result;
                }
                private static void _FileExtension_Validate(global::LightSwitchApplication.IssueDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.FileExtension_Validate(r);
                }
                private static string _FileExtension_GetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.FileExtension;
                }
                private static void _FileExtension_SetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d, string v)
                {
                    d.ImplementationEntity.FileExtension = v;
                }
                private static void _FileExtension_OnValueChanged(global::LightSwitchApplication.IssueDocument e)
                {
                    e.FileExtension_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>.Entry
                    IssueFile = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>.Entry(
                        "IssueFile",
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._IssueFile_Stub,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._IssueFile_ComputeIsReadOnly,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._IssueFile_Validate,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._IssueFile_GetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._IssueFile_SetImplementationValue,
                        global::LightSwitchApplication.IssueDocument.DetailsClass.PropertySetProperties._IssueFile_OnValueChanged);
                private static void _IssueFile_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.IssueDocument.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.IssueDocument.DetailsClass d, object sf)
                {
                    c(d, ref d._IssueFile, sf);
                }
                private static bool _IssueFile_ComputeIsReadOnly(global::LightSwitchApplication.IssueDocument e)
                {
                    bool result = false;
                    e.IssueFile_IsReadOnly(ref result);
                    return result;
                }
                private static void _IssueFile_Validate(global::LightSwitchApplication.IssueDocument e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IssueFile_Validate(r);
                }
                private static byte[] _IssueFile_GetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d)
                {
                    return d.ImplementationEntity.IssueFile;
                }
                private static void _IssueFile_SetImplementationValue(global::LightSwitchApplication.IssueDocument.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.IssueFile = v;
                }
                private static void _IssueFile_OnValueChanged(global::LightSwitchApplication.IssueDocument e)
                {
                    e.IssueFile_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>.Data _DocumentName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, string>.Data _FileExtension;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.IssueDocument, global::LightSwitchApplication.IssueDocument.DetailsClass, byte[]>.Data _IssueFile;
            
        }
    
        #endregion
    }
    
    #endregion
}
