

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class LogSource : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the LogSource entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LogSource()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LogSource(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LogSource> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.LogSource.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LogSource_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LogSource_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SourceName
        {
            get
            {
                return global::LightSwitchApplication.LogSource.DetailsClass.GetValue(this, global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties.SourceName);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SourceName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SourceName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SourceName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.LogEntry> EventEntries
        {
            get
            {
                return global::LightSwitchApplication.LogSource.DetailsClass.GetValue(this, global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties.EventEntries);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.LogEntry> EventEntriesQuery
        {
            get
            {
                return global::LightSwitchApplication.LogSource.DetailsClass.GetQuery(this, global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties.EventEntries);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.LogSource,
                global::LightSwitchApplication.LogSource.DetailsClass,
                global::LightSwitchApplication.LogSource.DetailsClass.IImplementation,
                global::LightSwitchApplication.LogSource.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties.SourceName;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass>.Entry
                __LogSourceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass>.Entry(
                    global::LightSwitchApplication.LogSource.DetailsClass.__LogSource_CreateNew,
                    global::LightSwitchApplication.LogSource.DetailsClass.__LogSource_Created,
                    global::LightSwitchApplication.LogSource.DetailsClass.__LogSource_AllowSaveWithErrors);
            private static global::LightSwitchApplication.LogSource __LogSource_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LogSource> es)
            {
                return new global::LightSwitchApplication.LogSource(es);
            }
            private static void __LogSource_Created(global::LightSwitchApplication.LogSource e)
            {
                e.LogSource_Created();
            }
            private static bool __LogSource_AllowSaveWithErrors(global::LightSwitchApplication.LogSource e)
            {
                bool result = false;
                e.LogSource_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.LogSource.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, string> SourceName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties.SourceName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, global::LightSwitchApplication.LogEntry> EventEntries
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties.EventEntries) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, global::LightSwitchApplication.LogEntry>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string SourceName { get; }
                new global::System.Collections.IEnumerable EventEntries { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, string>.Entry
                    SourceName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, string>.Entry(
                        "SourceName",
                        global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties._SourceName_Stub,
                        global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties._SourceName_ComputeIsReadOnly,
                        global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties._SourceName_Validate,
                        global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties._SourceName_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties._SourceName_OnValueChanged);
                private static void _SourceName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LogSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, string>.Data> c, global::LightSwitchApplication.LogSource.DetailsClass d, object sf)
                {
                    c(d, ref d._SourceName, sf);
                }
                private static bool _SourceName_ComputeIsReadOnly(global::LightSwitchApplication.LogSource e)
                {
                    bool result = false;
                    e.SourceName_IsReadOnly(ref result);
                    return result;
                }
                private static void _SourceName_Validate(global::LightSwitchApplication.LogSource e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SourceName_Validate(r);
                }
                private static string _SourceName_GetImplementationValue(global::LightSwitchApplication.LogSource.DetailsClass d)
                {
                    return d.ImplementationEntity.SourceName;
                }
                private static void _SourceName_OnValueChanged(global::LightSwitchApplication.LogSource e)
                {
                    e.SourceName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, global::LightSwitchApplication.LogEntry>.Entry
                    EventEntries = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, global::LightSwitchApplication.LogEntry>.Entry(
                        "EventEntries",
                        global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties._EventEntries_Stub,
                        global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties._EventEntries_GetReferencedEntities,
                        global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties._EventEntries_GetEntityCollection);
                private static void _EventEntries_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LogSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, global::LightSwitchApplication.LogEntry>.Data> c, global::LightSwitchApplication.LogSource.DetailsClass d, object sf)
                {
                    c(d, ref d._EventEntries, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.LogEntry> _EventEntries_GetReferencedEntities(global::LightSwitchApplication.LogSource.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.LogEntry, global::LightSwitchApplication.LogEntry.DetailsClass>(global::LightSwitchApplication.LogSource.DetailsClass.PropertySetProperties.EventEntries, ref d._EventEntries);
                }
                private static global::System.Collections.IEnumerable _EventEntries_GetEntityCollection(global::LightSwitchApplication.LogSource.DetailsClass d)
                {
                    return d.ImplementationEntity.EventEntries;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, string>.Data _SourceName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.LogSource, global::LightSwitchApplication.LogSource.DetailsClass, global::LightSwitchApplication.LogEntry>.Data _EventEntries;
            
        }
    
        #endregion
    }
    
    #endregion
}
