
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("ce48f73b-8dc6-48e0-b68a-e28acfc7bdb8")>
Namespace LightSwitchApplication.Implementation

    #Region "Contexts"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Partial Class AuditDataSource
        Inherits ObjectContext
    
        #Region "Constructors"
    
        ''' <summary>
        ''' Initializes a new AuditDataSource object using the connection string found in the 'AuditDataSource' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=AuditDataSource", "AuditDataSource")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new AuditDataSource object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "AuditDataSource")
            OnContextCreated()
        End Sub
    
        ''' <summary>
        ''' Initialize a new AuditDataSource object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "AuditDataSource")
            OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "Partial Methods"
    
        Partial Private Sub OnContextCreated()
        End Sub
    
        #End Region
    
        #Region "ObjectSet Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property AuditDetails() As ObjectSet(Of AuditDetail)
            Get
                If (_AuditDetails Is Nothing) Then
                    _AuditDetails = MyBase.CreateObjectSet(Of AuditDetail)("AuditDetails")
                End If
                Return _AuditDetails
            End Get
        End Property
    
        Private _AuditDetails As ObjectSet(Of AuditDetail)

        #End Region

        #Region "AddTo Methods"
    
        ''' <summary>
        ''' Deprecated Method for adding a new object to the AuditDetails EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
        ''' </summary>
        Public Sub AddToAuditDetails(ByVal auditDetail As AuditDetail)
            MyBase.AddObject("AuditDetails", auditDetail)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="LightSwitchApplication", Name:="AuditDetail")>
    <Serializable()>
    <DataContractAttribute(IsReference:=True)>
    Public Partial Class AuditDetail
        Inherits EntityObject
        #Region "Factory Method"
    
        ''' <summary>
        ''' Create a new AuditDetail object.
        ''' </summary>
        ''' <param name="auditID">Initial value of the AuditID property.</param>
        Public Shared Function CreateAuditDetail(auditID As Global.System.Int32) As AuditDetail
            Dim auditDetail as AuditDetail = New AuditDetail
            auditDetail.AuditID = auditID
            Return auditDetail
        End Function

        #End Region

        #Region "Primitive Properties"
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
        <DataMemberAttribute()>
        Public Property AuditID() As Global.System.Int32
            Get
                Return _AuditID
            End Get
            Set
                If (_AuditID <> Value) Then
                    OnAuditIDChanging(value)
                    ReportPropertyChanging("AuditID")
                    _AuditID = value
                    ReportPropertyChanged("AuditID")
                    OnAuditIDChanged()
                End If
            End Set
        End Property
    
        Private _AuditID As Global.System.Int32
        Private Partial Sub OnAuditIDChanging(value As Global.System.Int32)
        End Sub
    
        Private Partial Sub OnAuditIDChanged()
        End Sub
    
        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
        <DataMemberAttribute()>
        Public Property AuditDesc() As Global.System.String
            Get
                Return _AuditDesc
            End Get
            Set
                OnAuditDescChanging(value)
                ReportPropertyChanging("AuditDesc")
                _AuditDesc = value
                ReportPropertyChanged("AuditDesc")
                OnAuditDescChanged()
            End Set
        End Property
    
        Private _AuditDesc As Global.System.String
        Private Partial Sub OnAuditDescChanging(value As Global.System.String)
        End Sub
    
        Private Partial Sub OnAuditDescChanged()
        End Sub

        #End Region

    End Class

    #End Region

    
End Namespace
